<?php

namespace HedgeComm\EmailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{

	public function deleteCampaigns($campaigns)
	{
		$em = $this->getEntityManager();
	
		if (!is_array($campaigns)) 
		{
			$campaigns = array($campaigns);
		}
	
		foreach ($campaigns as $campaign)
		{
			$em->remove($campaign);
			$em->flush();
		}
	}

}
